In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

data = pd.read_csv("iris.csv")

X = data.drop("species", axis=1)
y = data["species"]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

model = DecisionTreeClassifier()
model.fit(X_train,y_train)

pred = model.predict(X_test)

print("Accuracy:",accuracy_score(y_test,pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,pred))

Accuracy: 1.0
Confusion Matrix:
 [[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

data = pd.read_csv("drug.csv")

X = data.drop("Drug",axis=1)
X = pd.get_dummies(X)   # convert categorical values
y = data["Drug"]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

model = DecisionTreeClassifier()
model.fit(X_train,y_train)

pred = model.predict(X_test)

print("Accuracy:",accuracy_score(y_test,pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,pred))

Accuracy: 1.0
Confusion Matrix:
 [[ 3  0  0  0  0]
 [ 0  1  0  0  0]
 [ 0  0  3  0  0]
 [ 0  0  0 14  0]
 [ 0  0  0  0 19]]


In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

data = pd.read_csv("petrol_consumption.csv")

X = data.drop("Petrol_Consumption",axis=1)
y = data["Petrol_Consumption"]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

model = DecisionTreeRegressor()
model.fit(X_train,y_train)

pred = model.predict(X_test)

print("MAE:",mean_absolute_error(y_test,pred))
print("MSE:",mean_squared_error(y_test,pred))
print("RMSE:",np.sqrt(mean_squared_error(y_test,pred)))

MAE: 54.2
MSE: 5157.0
RMSE: 71.81225522151495
